INNERTUBE_REQUEST_CLIENT_VERSION: str = "18.31.35"
INNERTUBE_REQUEST_ANDROID_SDK_VERSION: int = 30
INNERTUBE_REQUEST_API_KEY: str = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
ANDROIDTUBE_REQUEST_USER_AGENT: str = (
    "com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip"
)
